# Generated by Django 3.2.5 on 2021-12-08 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_profile_user_referring'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_referring',
            new_name='user',
        ),
    ]
