# Generated by Django 3.2.5 on 2021-08-25 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='myTag',
        ),
    ]
